import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import toast from 'react-hot-toast'
import { ArrowLeft, Plus, Trash2, Sparkles } from 'lucide-react'
import { getCourse, getCOs, getPOs, getPSOs, createCOsBulk, deleteCO, generateCOs } from '../api'
import PageHeader from '../components/PageHeader'
import Card from '../components/Card'
import Badge from '../components/Badge'

const bloomColors = { Remember:'slate', Understand:'blue', Apply:'green', Analyze:'purple', Evaluate:'orange', Create:'red' }

export default function CourseDetail() {
  const { id } = useParams()
  const [course, setCourse] = useState(null)
  const [cos, setCos] = useState([])
  const [pos, setPos] = useState([])
  const [psos, setPsos] = useState([])
  const [showForm, setShowForm] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [form, setForm] = useState({ code: '', description: '', bloom_level: 'Understand', po_ids: [], pso_ids: [] })

  const load = async () => {
    const [c, coList, poList, psoList] = await Promise.all([getCourse(id), getCOs(id), getPOs(), getPSOs()])
    setCourse(c.data); setCos(coList.data); setPos(poList.data); setPsos(psoList.data)
  }

  useEffect(() => { load() }, [id])

  const handleCreate = async (e) => {
    e.preventDefault()
    try {
      await createCOsBulk(id, { cos: [form] })
      toast.success('CO created')
      setShowForm(false)
      setForm({ code: '', description: '', bloom_level: 'Understand', po_ids: [], pso_ids: [] })
      load()
    } catch { toast.error('Failed') }
  }

  const handleGenerate = async () => {
    setGenerating(true)
    try {
      const poIds = pos.map(p => p.id)
      const psoIds = psos.map(p => p.id)
      await generateCOs(id, { course_id: id, po_ids: poIds, pso_ids: psoIds })
      toast.success('COs generated by AI')
      load()
    } catch { toast.error('AI generation failed. Check OpenAI key.') }
    setGenerating(false)
  }

  const handleDelete = async (coId) => {
    await deleteCO(id, coId)
    toast.success('CO deleted')
    load()
  }

  const toggleId = (list, setList, val) => {
    setList(prev => prev.includes(val) ? prev.filter(x => x !== val) : [...prev, val])
  }

  if (!course) return <div className="text-violet-300 p-8">Loading...</div>

  return (
    <div>
      <Link to="/courses" className="flex items-center gap-1 text-sm text-violet-400 hover:text-indigo-700 mb-4">
        <ArrowLeft className="w-4 h-4" /> Back to Courses
      </Link>
      <PageHeader title={course.name} subtitle={course.code}
        action={
          <div className="flex gap-2">
            <button onClick={handleGenerate} disabled={generating}
              className="flex items-center gap-2 gradient-btn text-white px-4 py-2 rounded-lg text-sm font-medium  disabled:opacity-50">
              <Sparkles className="w-4 h-4" /> {generating ? 'Generating...' : 'AI Generate COs'}
            </button>
            <button onClick={() => setShowForm(!showForm)}
              className="flex items-center gap-2 gradient-btn text-white px-4 py-2 rounded-lg text-sm font-medium ">
              <Plus className="w-4 h-4" /> Add CO
            </button>
          </div>
        } />

      {showForm && (
        <Card className="p-5 mb-6">
          <h2 className="font-semibold text-indigo-800 mb-4">Add Course Outcome</h2>
          <form onSubmit={handleCreate} className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <input required placeholder="CO Code (e.g. CO1)" value={form.code}
                onChange={e => setForm({ ...form, code: e.target.value })}
                className="border border-violet-100 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-300" />
              <select value={form.bloom_level} onChange={e => setForm({ ...form, bloom_level: e.target.value })}
                className="border border-violet-100 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-300">
                {['Remember','Understand','Apply','Analyze','Evaluate','Create'].map(l => <option key={l}>{l}</option>)}
              </select>
            </div>
            <textarea required placeholder="CO Description" value={form.description}
              onChange={e => setForm({ ...form, description: e.target.value })} rows={2}
              className="w-full border border-violet-100 rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-violet-300" />
            <div>
              <p className="text-xs font-medium text-indigo-700 mb-1">Map to POs</p>
              <div className="flex flex-wrap gap-2">
                {pos.map(p => (
                  <button type="button" key={p.id} onClick={() => toggleId(form.po_ids, (fn) => setForm(f => ({ ...f, po_ids: fn(f.po_ids) })), p.id)}
                    className={`px-2 py-1 rounded text-xs border transition ${form.po_ids.includes(p.id) ? 'bg-indigo-600 text-white border-indigo-600' : 'border-violet-100 text-indigo-700 hover:border-indigo-300'}`}>
                    {p.code}
                  </button>
                ))}
              </div>
            </div>
            <div>
              <p className="text-xs font-medium text-indigo-700 mb-1">Map to PSOs</p>
              <div className="flex flex-wrap gap-2">
                {psos.map(p => (
                  <button type="button" key={p.id} onClick={() => toggleId(form.pso_ids, (fn) => setForm(f => ({ ...f, pso_ids: fn(f.pso_ids) })), p.id)}
                    className={`px-2 py-1 rounded text-xs border transition ${form.pso_ids.includes(p.id) ? 'bg-violet-600 text-white border-violet-600' : 'border-violet-100 text-indigo-700 hover:border-purple-300'}`}>
                    {p.code}
                  </button>
                ))}
              </div>
            </div>
            <div className="flex gap-2">
              <button type="submit" className="gradient-btn text-white px-4 py-2 rounded-lg text-sm font-medium ">Save</button>
              <button type="button" onClick={() => setShowForm(false)} className="px-4 py-2 rounded-lg text-sm text-indigo-700 hover:bg-violet-50">Cancel</button>
            </div>
          </form>
        </Card>
      )}

      <div className="space-y-3">
        {cos.map(co => (
          <Card key={co.id} className="p-4">
            <div className="flex items-start justify-between">
              <div className="flex items-start gap-3">
                <span className="bg-violet-100 text-indigo-800 font-bold text-sm px-2.5 py-1 rounded-lg">{co.code}</span>
                <div>
                  <p className="text-sm text-indigo-800">{co.description}</p>
                  <div className="flex flex-wrap gap-1.5 mt-2">
                    {co.bloom_level && <Badge label={co.bloom_level} color={bloomColors[co.bloom_level] || 'slate'} />}
                    {co.po_ids?.map(pid => {
                      const po = pos.find(p => p.id === pid)
                      return po ? <Badge key={pid} label={po.code} color="blue" /> : null
                    })}
                    {co.pso_ids?.map(pid => {
                      const pso = psos.find(p => p.id === pid)
                      return pso ? <Badge key={pid} label={pso.code} color="purple" /> : null
                    })}
                  </div>
                </div>
              </div>
              <button onClick={() => handleDelete(co.id)} className="text-red-400 hover:text-red-600 ml-2">
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          </Card>
        ))}
        {cos.length === 0 && (
          <div className="text-center py-12 text-violet-300">
            <p>No COs yet. Add manually or use AI Generate.</p>
          </div>
        )}
      </div>
    </div>
  )
}
